### ISSUE TITLE
Highscore

### ISSUE THREAD

**Issue by rfajfar** [mirkodin/zmija#2]
Sistem za highscore.

Score se shrani gda igro zapereš.

Naloži se ob zagoni igre.

**Comment by Qsterix** [comment]
Kul

2016-03-15 19:14 GMT+01:00 Rok Fajfar <notifications@github.com>:

**Comment by rfajfar** [comment]
Ful kul.

**Comment by rfajfar** [comment]
V večini nareto, v `Scripts/score.py`.

**Comment by rfajfar** [comment]
V fajl naj se shrani samo najboljših 5 rezultatov recimo.

**Comment by rfajfar** [comment]
Done.

**Comment by Qsterix** [comment]
spaaaaam
Dne 23. mar. 2016 17:28 je "Rok Fajfar" <notifications@github.com>
napisal/-a:

**Comment by rfajfar** [comment]
Kej dugi cejt van je?
