### ISSUE TITLE
Sprajti

### ISSUE THREAD

**Issue by rokf** [mirkodin/zmija#8]
Nekatere kocke zamenjamo s slikami. Dodamo neko pattern ozadje namesto črnega.

**Comment by Qsterix** [comment]
pepsiji?
Dne 23. mar. 2016 18:16 je "Rok Fajfar" <notifications@github.com>
napisal/-a:

**Comment by rfajfar** [comment]
Juice Vodka

**Comment by rokf** [comment]
Done
